export const SET_WX="SET_WX"; 
export const SET_SWITCH_STATUS="SET_SWITCH_STATUS"; 
export const SET_ORGANIZATION="SET_ORGANIZATION"; 
export const SET_FRAMEDATA="SET_FRAMEDATA"; 
export const SET_USERNAME="SET_USERNAME"; 
